name: inat_cv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - seaborn
  - matplotlib
  - duckdb
  - optuna
  - mlflow
  - ipykernel          # Required for VS Code Jupyter to work correctly
  - pip:
    - --index-url https://download.pytorch.org/whl/cu118
    - torch
    - torchvision
    - torchaudio
    - -e ".[dev]"      # Your local dev installation
