name: inat_cv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pandas
  - seaborn
  - matplotlib
  - duckdb
  - optuna
  - mlflow
  - ipykernel          # Required for VS Code Jupyter to work correctly
  - pip:
    - -e ".[dev]"      # Your local dev installation
