[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "plant_pheno"
version = "0.0.1"
description = "Plant phenology classification with transfer learning"
authors = [{ name="Etienne Godin", email="etiennegodin@duck.com" }]


# Base dependencies — sufficient for inference
dependencies = [
    "torch",
    "torchvision",
    "timm",
    "open-clip-torch",
    "pyyaml",
    "tqdm",
]

[project.optional-dependencies]
# Full training dependencies
train = [
    "pandas>=2.2,<2.4",
    "matplotlib>=3.10,<3.11",
    "duckdb>=1.5,<1.6",
    "optuna>=4.8,<4.9",
    "scikit-learn>=1.7,<1.8",
    "mlflow>=3.11,<3.12",
    "seaborn",
    "python-dotenv",
]

dev = [
    "pytorch_pipeline[train]",  # dev includes train
    "pytest",
    "pytest-cov",
    "pytest-dependency",
    "ruff",
    "dvc",
    "jupyterlab",
    "pre-commit",
    "ipykernel",
    "ipywidgets",
    "cleanlab",
]

[project.scripts]   # <-- entry point CLI
torch_pipe = "plant_pheno.cli:main"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
# E: pycodestyle errors, F: Pyflakes, I: isort (imports)
select = ["E", "F", "I"]
fixable = ["ALL"]
unfixable = ["F401"]

[tool.ruff.format]
# Matches Black's default style
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
python_version = "3.11"
strict = true

[tool.pytest.ini_options]
addopts = "--cov=src/plant_pheno --cov-report=term-missing --cov-report=html -s"
[tool.sqlfluff.core]
dialect = "duckdb"
templater = "placeholder"
rules = "layout"
exclude_rules = "AM04, AL05, LT05"
