[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "pytorch_pipeline"
version = "0.0.1"
description = "Pytorch inat vision"
authors = [{ name="Etienne Godin", email="etiennegodin@duck.com" }]

dependencies = [
    "pandas>=2.2,<2.4",
    "matplotlib>=3.10,<3.11",
    "duckdb>=1.5,<1.6",
    "optuna>=4.8,<4.9",
    "scikit-learn>=1.7,<1.8",
    "mlflow>=3.11,<3.12",
    "open-clip-torch",
    "seaborn",
    'pyyaml',
    "tqdm",
    "python-dotenv",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-dependency",
    "ruff",
    "dvc",
    "jupyterlab",
    "pre-commit",
    "ipykernel",          # Required for VS Code Jupyter to work correctly
    "ipywidgets",
    "cleanlab"

]

[project.scripts]   # <-- entry point CLI
torch_pipe = "pytorch_pipeline.cli:main"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
# E: pycodestyle errors, F: Pyflakes, I: isort (imports)
select = ["E", "F", "I"]
fixable = ["ALL"]
unfixable = ["F401"]

[tool.ruff.format]
# Matches Black's default style
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
python_version = "3.11"
strict = true

[tool.pytest.ini_options]
addopts = "--cov=src/pytorch_pipeline --cov-report=term-missing --cov-report=html -s"
[tool.sqlfluff.core]
dialect = "duckdb"
templater = "placeholder"
rules = "layout"
exclude_rules = "AM04, AL05, LT05"
