paths :
  root : '/content/inat-phenology-cv'
  data_root : '/content/inat-phenology-cv/data'
  image_dir : '/content/images'
  db_path : '/content/data/cv_raw.duckdb'
  checkpoint_path : '/content/inat-phenology-cv/data/checkpoints/checkpoint.pth'

dataloader_params:
    batch_size: 256
    max_images: 1024
    num_workers: 2
    pin_memory: true
    persistent_workers: true
    use_max_images : true
