paths :
  root : '/content/inat-phenology-cv'
  data_root : '/content/inat-phenology-cv/data'
  image_dir : '/content/images'

dataloader_params:
    batch_size: 32
    max_images: 32
    num_workers: 2
    pin_memory: true
    persistent_workers: true
    use_max_images : false
