paths :
  root : '/home/etienne/projects/inat-phenology-cv/'
  data_root : '/home/etienne/projects/inat-phenology-cv/data'
  image_dir : '/home/etienne/projects/inat-phenology-cv/data/images'
  db_path : '/home/etienne/projects/inat-phenology-cv/data/cv_photos3.parquet'
  checkpoint_path : '/home/etienne/projects/inat-phenology-cv/data/checkpoints'

dataset_params:
  source_table : "cv_photos3"
  idx_col: "observation_id"
  photo_idx_col: "photo_id"
  label_col: "label"

dataloader_params:
    batch_size: 32
    max_images: 128
    num_workers: 4
    pin_memory: false
    persistent_workers: false
    use_max_images : true
