paths :
  root : '/home/etienne/projects/inat-phenology-cv/'
  data_root : '/home/etienne/projects/inat-phenology-cv/data'
  image_dir : '/home/etienne/projects/inat-phenology-cv/data/images'
  db_path : '/home/etienne/projects/inat-phenology-cv/data/cv_raw.duckdb'
  checkpoint_path : '/home/etienne/projects/inat-phenology-cv/data/checkpoints/checkpoint.pth'
  ml_flow_db : '/home/etienne/projects/inat-phenology-cv/data/mlflow.db'

dataloader_params:
    batch_size: 32
    max_images: 128
    num_workers: 4
    pin_memory: false
    persistent_workers: false
    use_max_images : true
